version: '3'

services:
  mosquitto:
    build:
      context: .
      dockerfile: Containerfile.mosquitto
    container_name: mosquitto
    network_mode: host
    privileged: true
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto_log:/mosquitto/log
    environment:
      - REMOTE_ADDRESS=REMOTE_BROKER:1883 # Replace this with the IP address of your remote MQTT broker
      - REMOTE_USERNAME=BROKER_USER       # Replace this with the username of your remote MQTT broker
      - REMOTE_PASSWORD=BROKER_PASS       # Replace this with the password of your remote MQTT broker

  mosquitto-subscriber:
    image: eclipse-mosquitto:latest
    container_name: mosquitto-subscriber
    network_mode: host
    command: mosquitto_sub -h mosquitto -t "#" -v
    depends_on:
      - mosquitto

  putting-app:
    build:
      context: .
      dockerfile: Containerfile.app
    container_name: putting-app
    network_mode: host
    privileged: true
    devices:
      # - /dev/bus/usb:/dev/bus/usb  # Forward USB devices
      # - /dev/ttyUSB0:/dev/ttyUSB0  # Forward a specific USB device, modify as per your actual device
    volumes:
      - ./app:/app
    command: python3 /app/main.py
    characteristics:
        cap_add:
          - NET_ADMIN
          - SYS_ADMIN
    environment:
      - MQTT_BROKER=mosquitto
      - BLE_ID=PL2B2118 # Replace this with the ID of your golfball. You can get this by using the scan.py script in the app folder
                        # Run 'python3 scan.py "^PL"' and it will scan for the golf ball and list out its characteristics
                        # The complete BLE ID is shown near the top of the output and starts with PL
